
name: Test coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Generate coverage report
      run: mvn -B verify -P coverage --no-transfer-progress
    - uses: codecov/codecov-action@v1
      with:
        file: ./target/site/jacoco/jacoco.xml
